In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("test_data.csv")

In [3]:
df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
3,794,795,0,1,0.3125,0.015412,0,0,1,0.0,1,0,0,0,0,0,1
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1

In [4]:
df.tail()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

In [5]:
df.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00,100.00000,100.000000,100.00000,100.000000,100.000000
mean,840.500000,841.500000,0.360000,0.650000,0.355656,0.048333,0.230000,0.200000,0.57000,0.104000,0.770000,0.01,0.08000,0.140000,0.21000,0.040000,0.740000
std,29.011492,29.011492,0.482418,0.479372,0.161188,0.053429,0.422953,0.402015,0.49757,0.207885,0.422953,0.10,0.27266,0.348735,0.40936,0.196946,0.440844
min,791.000000,792.000000,0.000000,0.000000,0.005250,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
25%,815.750000,816.750000,0.000000,0.000000,0.271875,0.015412,0.000000,0.000000,0.00000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
50%,840.500000,841.500000,0.000000,1.000000,0.350000,0.025374,0.000000,0.000000,1.00000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
75%,865.250000,866.250000,1.000000,1.000000,0.426563,0.058556,0.000000,0.000000,1.00000,0.100000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
max,890.000000,891.000000,1.000000,1.000000,0.925000,0.321798,1.000000,1.000000,1.00000,1.000000,1.000000,1.00,1.00000,1.000000,1.00000,1.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   100 non-null    int64
 1   PassengerId  100 non-null    int64
 2   Survived     100 non-null    int64
 3   Sex          100 non-null    int64
 4   Age          100 non-null    float64
 5   Fare         100 non-null    float64
 6   Pclass_1     100 non-null    int64
 7   Pclass_2     100 non-null    int64
 8   Pclass_3     100 non-null    int64
 9   Family_size  100 non-null    float64
 10  Title_1      100 non-null    int64
 11  Title_2      100 non-null    int64
 12  Title_3      100 non-null    int64
 13  Title_4      100 non-null    int64
 14  Emb_1        100 non-null    int64
 15  Emb_2        100 non-null    int64
 16  Emb_3        100 non-null    int64
dtypes: float64(3), int64(14)
memory usage: 13.4 KB

In [7]:
df.isnull().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Sex            0
Age            0
Fare           0
Pclass_1       0
Pclass_2       0
Pclass_3       0
Family_size    0
Title_1        0
Title_2        0
Title_3        0
Title_4        0
Emb_1          0
Emb_2          0
Emb_3          0
dtype: int64

In [8]:
df.isnull()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.shape()

TypeError: 'tuple' object is not callable

In [10]:
df.shape

(100, 17)

In [11]:
df.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Sex              int64
Age            float64
Fare           float64
Pclass_1         int64
Pclass_2         int64
Pclass_3         int64
Family_size    float64
Title_1          int64
Title_2          int64
Title_3          int64
Title_4          int64
Emb_1            int64
Emb_2            int64
Emb_3            int64
dtype: object

In [17]:
df['Sex']=df['Sex'].astype(string)

NameError: name 'string' is not defined

In [14]:
df['Sex']=df['Sex'].map({'0':'male','1':'female'})

In [15]:
df.tail()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
95,886,887,0,NaN,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,NaN,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,NaN,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,NaN,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,NaN,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0