In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('tips')

In [3]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
grouped=df.groupby('day')['total_bill'].describe()

/tmp/ipykernel_774/3293860533.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped=df.groupby('day')['total_bill'].describe()

In [8]:
print(grouped)

      count       mean       std   min      25%    50%      75%    max
day
Thur   62.0  17.682742  7.886170  7.51  12.4425  16.20  20.1550  43.11
Fri    19.0  17.151579  8.302660  5.75  12.0950  15.38  21.7500  40.17
Sat    87.0  20.441379  9.480419  3.07  13.9050  18.24  24.7400  50.81
Sun    76.0  21.410000  8.832122  7.25  14.9875  19.63  25.5975  48.17

In [9]:
grouped_list=df.groupby('day')['total_bill'].apply(list)

/tmp/ipykernel_774/3629004054.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_list=df.groupby('day')['total_bill'].apply(list)

In [10]:
print(grouped_list)

day
Thur    [27.2, 22.76, 17.29, 19.44, 16.66, 10.07, 32.6...
Fri     [28.97, 22.49, 5.75, 16.32, 22.75, 40.17, 27.2...
Sat     [20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17....
Sun     [16.99, 10.34, 21.01, 23.68, 24.59, 25.29, 8.7...
Name: total_bill, dtype: object

In [11]:
df=sns.load_dataset('iris')

In [13]:
setosa = df[df['species'] == 'setosa']
versicolor = df[df['species'] == 'versicolor']

In [14]:
setosa.describe()

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

In [15]:
versicolor.describe()

       sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000